version: '2'

services:

  elasticsearch:
    build: .
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  cerebro:
    image: yannart/cerebro:0.6.6
    ports:
      - "9000:9000"
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:

  elastic:
    driver: bridge
